trigger:
- main

pool:
  vmImage: 'ubuntu-latest' 

steps:
  - task: Bash@3
    displayName: 'Fetch and Run HyperExecute'
    inputs:
      targetType: 'inline'
      script: |
        # Download Hyperexecute CLI for Linux (matching your ubuntu-latest pool)
        wget https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute
        
        # Grant execute permission to the downloaded binary
        chmod +x hyperexecute
        
        # Run Hyperexecute with user credentials and configuration file
        ./hyperexecute --user $(LT_USERNAME) --key $(LT_ACCESS_KEY) --config yaml/autosplit_linux.yaml
